name: doghog
description: DogHog MVP
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/dog/
    - assets/images/food/
    - assets/images/ui/
    - assets/animations/dog/
    - assets/sounds/
