name: doghog
description: DogHog MVP
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food/
    - assets/bowls/
    - assets/dogs/
    - assets/dogs/mrozek/
    - assets/dogs/mrozek/video/
    - assets/dogs/mrozek/images/
    - assets/pipes/
    - assets/backgrounds/
    - assets/audio/
